[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PySparseCoalescedTsetlinMachineCUDA"
version = "0.2.0.22"
dependencies = [
    "numpy",
    "pycuda",
    "scipy",
]
readme = "README.md"
dynamic = [
    "description",
    "authors",
    "license",
    "keywords",
]

[tool.setuptools.package-data]
"*" = ["cuda/*.cu"]

[tool.basedpyright]
typeCheckingMode = "standard"
reportUnusedImport = false

[tool.ruff]
line-length = 160

[tool.ruff.format]
indent-style = "tab"
